# Generated by Django 5.1.6 on 2025-02-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Колір', 'verbose_name_plural': 'Кольори'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукти'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Картинка', 'verbose_name_plural': 'Картинкі'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Розмір', 'verbose_name_plural': 'Розміри'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
