# Generated by Django 5.1.6 on 2025-02-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_name_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='newPrice_Yes_No',
            field=models.BooleanField(blank=True, default=False, verbose_name='Показати Акцію'),
        ),
    ]
