# Generated by Django 5.1.6 on 2025-02-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_productimage_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
