# Generated by Django 5.1.6 on 2025-02-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_newprice_yes_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='newPrice_Yes_No',
            field=models.BooleanField(default=False, verbose_name='Показати Акцію'),
        ),
    ]
