# Generated by Django 5.1.6 on 2025-02-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_newprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='newPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Новаціна по Акцій'),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large'), ('XXXL', 'Extra Extra Extra Large')], max_length=4, unique=True),
        ),
    ]
